name: Haja API Test CI

on:
  push:
    branches: [ main ]  # atau ganti dengan branch yang kamu pakai

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run all testcases
      run: |
        python testcase/testcase1.py
        python testcase/testcase2.py
        python testcase/testcase3.py
